// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIpfQJVUMRM7YTttzy7mWja2TJdMT2GVI',
    appId: '1:831262760237:web:6c22d9a016a344b61fc7a4',
    messagingSenderId: '831262760237',
    projectId: 'e-wallet-45623',
    authDomain: 'e-wallet-45623.firebaseapp.com',
    storageBucket: 'e-wallet-45623.appspot.com',
    measurementId: 'G-N93M6BF038',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXUTDFM8ZjEYcmutXmUonnre0dck0F1MA',
    appId: '1:831262760237:android:c40d4d51379580d11fc7a4',
    messagingSenderId: '831262760237',
    projectId: 'e-wallet-45623',
    storageBucket: 'e-wallet-45623.appspot.com',
  );
}
